name: gongzuozs
options:
  bundleIdPrefix: com.gongzuozhushou
  deploymentTarget:
    iOS: "15.0"
targets:
  gongzuozs:
    type: application
    platform: iOS
    sources:
      - path: gongzuozs
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gongzuozhushou
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: gongzuozs/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
